language: ruby

rvm:
    - 2.0.0
    - 2.2.4
    - 2.2.6
    - 2.3.3
    - ruby-head

before_script:
    - gem install bundler

script:
    - bundle install
    - bundle exec rake test
    - rake doc
    - rake build
    - rake install

